---
- hosts: host1
  become: true
  become_user: root

  tasks:
  - name: Creating first partition
    parted:
      device: /dev/nvme0n2
      number: 1
      state: present
      part_end: 15GiB

  - name: Formating part partition
    filesystem:
      dev: /dev/nvme0n2p1
      fstype: xfs
      force: yes

  - name: Mounting First Partition
    mount:
      src: /dev/nvme0n2p1
      path: /partition
      fstype: xfs
      state: mounted

  
  - name: Creating remaining partition
    parted:
      device: /dev/nvme0n2
      number: 2
      state: present
      part_end: '100%'

  - name: Formating remaining partition
    filesystem:
      dev: /dev/nvme0n2p2
      fstype: xfs
      force: yes

  - name: Mounting remaining Partition
    mount:
      src: /dev/nvme0n2p2
      path: /partition-2
      fstype: xfs
      state: mounted
