---
- hosts: redhosts
  become: true
  become_user: root

  tasks:
  - name: Updating package manager
    yum:
      name: '*'
      state: latest

  - name: Install development tool
    yum:
      name: @RPM development tools
      state: latest
