---
- name: creating four partitions
  parted:
    device: /dev/nvme0n2
    number: "{{ item.number }}"
    state: present
    flags: [ lvm ]
    part_start: "{{ item.start }}"
    part_end: "{{ item.end }}"
  loop:
    - { number: "1",  start: "1MiB", end: "1GiB" } 
    - { number: "2",  start: "1GiB", end: "3GiB" } # 3GiB -1GiB = 2GiB
    - { number: "3",  start: "3GiB", end: "4GiB" } 
    - { number: "4",  start: "4GiB", end: "100%" } 
