---
- hosts: all
  become: true
  become_user: root

  vars:
  - new_port: '222'

  tasks:
  - name: Demo of sending changed ssh file to hosts
    template:
     src: /home/bsuman/ansible-redhat/ansible-galaxy/demo/sshd_config.j2
     dest: /home/bsuman/sshd_config
