---
#- hosts: kubernetes
#  become: true
#  become_user: root

#  tasks:
    - name: updating apt package, and installing required packages
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - iputils*
        - net-tools
        - aptitude
        - python3
        - python3-pip
        - python3-debian
    
    - name: updating timezone
      timezone:
        name: Asia/Kathmandu

    - name: upgrading all packages using aptitude
      shell: "aptitude full-upgrade -y"
      register: upgrade_output
      changed_when: "'Need to get' in upgrade_output.stdout"

    - name: Rebooting the system 
      reboot:
        msg: "Rebooting after a full system upgrade"
        reboot_timeout: 5  #rebooting after 5 seconds
      when: upgrade_output.changed
