---
- hosts: all

  tasks:
    - name: checking if vg 'research' exists
      debug:
        msg: "Vg 'research' not found"
      when: "ansible_lvm.vgs.research is not defined"

    - block:
      - name: creating lvm with size 1500M
        lvol:
          vg: research
          lv: data
          size: 1500M
        when: ansible_lvm.vgs.research.free_g >= "1.5"

      - name: when lvm not created
        debug:
          msg: "Insufficient vg size"
        when: ansible_lvm.vgs.research.free_g < "1.5"

      - name: creating lvm with size 800M
        lvol:
          vg: research
          lv: data
          size: 800M
        when: ansible_lvm.vgs.research.free_g < "1.5"

      when: "ansible_lvm.vgs.research is defined"

      always:
        - name: formating lvm
          filesystem:
            device: /dev/research/data
            fstype: ext4

        


      
