---
- hosts: redhosts
  become: true
  become_user: root

  tasks:
  - name: Installing services
    yum:
      name: "{{ item }} "
      state: latest
    loop:
    - tree
    - httpd
    - vsftpd
    - git
