---
- hosts: redhosts
  become: true
  become_user: root

  tasks:
  - name: Creating first partition
    parted:
      device: /dev/nvme0n2
      number: 1
      state: present
      part_end: 15GiB

  - name: Formating part partition
    filesystem:
      device: /dev/nvme0n2p1
      fstype: xfs
      force: yes

  - name: Mounting First Partition
    mount:
      src: /dev/nvme0n2p1
      path: /partition
      fstype: xfs
      state: mounted

  
  - name: Creating remaining partition
    parted:
      device: /dev/nvme0n2
      number: 2
      state: present
      part_start: 15GiB
        # partition will start at the 15 gibibyte (GiB) mark within the storage device. Tt will start after the initial 15GiB and use space beyond that point.
      part_end: '100%'
    tags:
    - part  

  - name: Formating remaining partition
    filesystem:
      device: /dev/nvme0n2p2
      fstype: xfs
      force: yes

  - name: Mounting remaining Partition
    mount:
      src: /dev/nvme0n2p2
      path: /partition-2
      fstype: xfs
      state: mounted
