---
- hosts: all

  tasks:
    - block:
      - name: creating /dev/nvme0n2p1 with 1600M size
        parted:
          device: /dev/nvme0n2
          number: 1
          state: present
          part_end: 1600MiB
        when: ansible_devices.nvme0n2.size >= "1.6BiB"

      - name: when disk not created
        debug:
          msg: "insufficient size"
        when: ansible_devices.nvme0n2.size < "1.6BiB"

      - name: creating disk with 900M size
        parted:
          device: /dev/nvme0n2
          number: 1
          state: present
          part_end: 900MiB
      when: "'nvme0n2' is in ansible_devices"

      rescue:
      - name: check if disk exists
        debug:
          msg: "Disk not found"

      always:
        - name: formating file system
          filesystem:
            device: /dev/nvme0n2p1
            fstype: ext4
            force: yes

        - name: creating mount point
          file:
            name: /part
            state: directory

        - name: mounting partition
          mount:
            src: /dev/nvme0n2p1
            path: /part
            fstype: ext4
            state: mounted

      
