---
- hosts: all
  become: true
  become_user: root

  tasks:
  - name: Creating Groups
    group:
      name: "{{ item }}"
      state: present
    loop:
      - techgeeks
      - marvel
      - dcuniverse

  - name: Creating users and adding to groups
    user:
     name : "{{ item.name }}"
     password: "{{ item.password }}"
     state: present
     groups: "{{ item.groups }}"
    loop:
      - { name: "elon", groups: "techgeeks", password: "{{ 'techgeeks' | password_hash('sha512') }}" }
      - { name: "mark", groups: "techgeeks", password: "{{ 'techgeeks' | password_hash('sha512') }}" }
      - { name: "jeff", groups: "techgeeks" ,password: "{{ 'techgeeks' | password_hash('sha512') }}" }
      - { name: "hugh", groups: "marvel", password: "{{ 'marvel' | password_hash('sha512') }}"}
      - { name: "chris", groups: "marvel", password: "{{ 'marvel' | password_hash('sha512') }}"}
      - { name: "robert", groups: "marvel", password: "{{ 'marvel' | password_hash('sha512') }}"}
      - { name: "jason", groups: "dcuniverse", password: "{{ 'dcuniverse' | password_hash('sha512') }}"}
      - { name: "ben", groups: "dcuniverse", password: "{{ 'dcuniverse' | password_hash('sha512') }}"}
      - { name: "clerk", groups: "dcuniverse", password: "{{ 'dcuniverse' | password_hash('sha512') }}"}

