---
- hosts: redhosts
  become: true
  become_user: root
  vars_files:
  #location of file
  - pass.yaml

  tasks:
  - name: Creating User and Saving password to Vault
    user:
      name: testuser
      #unsecure open method of setting user password 
      ##password: "ff 'suman' | password_hash('sha512') }}"
      
      #retriving password from password.txt
      password: "{{ user_password | password_hash('sha512') }}"
      state: present
        
