---
- hosts: host1
  become: true
  become_user: root

  tasks:
  - name: copying file
    copy:
      src: /etc/group
      dest: /home/bsuman/ansible
      owner: suman
      group: netops
  
  - name: Archiving file
    archive:
      path: /home/bsuman/ansible/group
      dest: /home/bsuman/ansible/group.tar
      owner: suman
      group: netops

  - name: Unarchiving file
    unarchive:
      src: /home/bsuman/ansible/group.tar
      dest: /home/bsuman/
      remote_src: yes
    tags: unzip
