---
- hosts: host1
  become: true
  become_user: root

  tasks:
  - name: Creating Logical Volume Group
    lvg:
      pvs: /dev/nvme0n2
      vg: vg1
      state: present

  - name: Creating Logical Volume
    lvol:
      vg: vg1
      lv: lv1
      state: present
      size: 15G

  - name: Formating the volume
    filesystem:
      dev: /dev/vg1/lv1
      fstype: xfs
      force: yes

  - name: Mounting the volume partition
    mount:
      src: /dev/vg1/lv1
      path: /logical-partition
      fstype: xfs
      state: mounted

