---
- hosts: host1
  become: true
  become_user: root

  tasks:
  - name: mounting host1
    mount:
     src: /dev/sr0
     path: /mount
     state: mounted
     fstype: iso9660

  - name: Install packages
    yum:
     name: httpd
     state: latest

  - name: Start and enable httpd 
    service:
     name: httpd
     state: started
     enabled: true

  - name : Permit in firewall
    firewalld:
      service: http
      permanent: true
      immediate: yes
      state: enabled
    tags:
    - firewall

