---
- hosts: all
  become: true
  become_user: root

  tasks:
  - name: Installing services to Redhat
    yum:
      name: "{{ item }} "
      state: latest
    loop:
    - tree
    - httpd
    - vsftpd
    - git
    when: ansible_os_family == "RedHat"

  - name: Installing services to Debian
    apt:
      name: "{{ item }} "
      state: latest
    loop:
    - tree
    - apache2
    - vsftpd
    - git
    when: ansible_os_family == "Debian"
