---
- hosts: all
  become: true
  become_user: root

  tasks:
  - name: Installing services to group redhosts
    yum:
      name: "{{ item }} "
      state: latest
    loop:
    - tree
    - httpd
    - vsftpd
    - git
    when: inventory_hostname in groups['redhosts']

  - name: Installing services to group ubuntuhosts
    apt:
      name: "{{ item }} "
      state: latest
    loop:
    - tree
    - apache2
    - vsftpd
    - git
    when: inventory_hostname in groups['ubuntuhosts']
